<?php

namespace MobileOne\WSservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SongRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundRepository extends EntityRepository
{
}
