<?php

namespace MobileOne\WSservationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class userController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MobileOne\WSservationBundle\Controller\userController();
        return $instance;
    }
}
